"""difficulty

Revision ID: 10a5d4fabb8f
Revises: 9eeccf9712d2
Create Date: 2021-09-18 21:02:00.780863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a5d4fabb8f'
down_revision = '9eeccf9712d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
