"""#

Revision ID: 29590a45fc22
Revises: 03eeba6f9ee8
Create Date: 2021-05-13 11:40:33.245079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29590a45fc22'
down_revision = '03eeba6f9ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'is_published')
    # ### end Alembic commands ###
