"""test_table

Revision ID: 296b0034f245
Revises: 8c3d1fa5fffe
Create Date: 2021-09-19 09:47:03.766820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296b0034f245'
down_revision = '8c3d1fa5fffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    # ### end Alembic commands ###
