"""#

Revision ID: 4692c5702ad0
Revises: 29590a45fc22
Create Date: 2021-05-13 11:41:42.841916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4692c5702ad0'
down_revision = '29590a45fc22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group') as batch_op:
        batch_op.drop_column('is_published')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('is_published', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
