"""level

Revision ID: 8c3d1fa5fffe
Revises: e22d7811ab51
Create Date: 2021-09-18 21:49:27.103003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3d1fa5fffe'
down_revision = 'e22d7811ab51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
