"""added display problemset

Revision ID: be4bb15e0d45
Revises: f54786209527
Create Date: 2021-08-28 12:49:07.360660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4bb15e0d45'
down_revision = 'f54786209527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('display_problemset', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'display_problemset')
    # ### end Alembic commands ###
