"""lla

Revision ID: ccbd61a40b9a
Revises: 10a5d4fabb8f
Create Date: 2021-09-18 21:31:48.283240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbd61a40b9a'
down_revision = '10a5d4fabb8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('qqq', sa.Integer(), nullable=True))
    op.drop_column('problem', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('level', sa.INTEGER(), nullable=True))
    op.drop_column('problem', 'qqq')
    # ### end Alembic commands ###
