"""level

Revision ID: e22d7811ab51
Revises: ccbd61a40b9a
Create Date: 2021-09-18 21:40:22.026514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22d7811ab51'
down_revision = 'ccbd61a40b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'qqq')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('qqq', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
